### ISSUE TITLE
Help Pages

### ISSUE THREAD

**Issue by tommoor** [speak/website#52]
This issue is for discussing implementation of a knowledgebase and which content / categories we want to have.

**Comment by ericbieller** [comment]
Speak Overview
- What is Speak?
- Who is Speak for?

Audio / Video Calls
- Instant Answer vs Call & Accept
- How to have an audio call
- How to have a video call
- How to have a group call
- Screensharing
- Changing your camera / microphone

Teams
- Creating a new team
- Joining multiple Slack teams
- Leaving a team
- Switching between teams
- Inviting (tbd)

The People Dock
- Docking / Undocking Speak to your screen
- Changing the Dock theme and position

Other
- Custom status messages
- Changing your availability (Instant Answer / Call & Accept)
- How does team presence work?

Reporting issues
- Link to github public issues

**Comment by willbarrett** [comment]
Suggestion: Showing in the dock vs. as a tray icon

**Comment by willbarrett** [comment]
Also, under Reporting Issues, let's include the howdy@speak.io email address as well. Some folks don't have github accounts :scream:

**Comment by ericbieller** [comment]
Good ideas, dun

**Comment by tommoor** [comment]
@ericbieller what's the plan with this one... shall we set a goal to get enough content in here so that we can link to it by the end of the week? I can put a link in the next app release.
