### ISSUE TITLE
Everything you need section doesn't match app design

### ISSUE THREAD

**Issue by awsmsrc** [speak/website#54]
Came up in live chat, customer was dissapoint

![screen shot 2015-08-31 at 11 04 22 am](https://cloud.githubusercontent.com/assets/994907/9576517/31008e66-4fd0-11e5-858a-d704cb3330bf.png)

**Comment by tommoor** [comment]
Why doesn't match about it?

**Comment by willbarrett** [comment]
I think it's easy to misconstrue this image as the entire desktop, instead of the video window.

**Comment by ericbieller** [comment]
@awsmsrc was there more to this or was @willbarrett correct?

**Comment by awsmsrc** [comment]
pretty sure @willbarrett was correct. I was just relaying what someone in support said, I think they wanted the chat heads to appear on THEIR desktop like that

**Comment by tommoor** [comment]
Closing this. I can see the issue but we'll wait until next homepage iteration to change the image, i don't think it's that confusing to most - plus there is text that clearly explains.
