### ISSUE TITLE
Allow signin on invite acceptance page

### ISSUE THREAD

**Issue by tommoor** [speak/website#67]
In order for people that already have an account to accept organization invites we need to let them sign in on this page as previously discussed. This has already come up in support. 

It also means that if someone gets an invite to an email address that they don't have a speak account under, they have the opportunity to login instead and accept the invite under their existing account instead of being forced to create another one.

The option to login should be added at the bottom of the form (similar to how it is in app) - The form can then change to show an email/password field.

Related to #51

**Comment by awsmsrc** [comment]
Looking forward to this one @tommoor much more in my skill set ;)

There is a bit more scope information I need before I can make a really good go of this. Though I'm going to start under the assumption Bulldog has everything we need for a bare min

Exactly what information do they need to see here?
I have a feeling that all the information they need won't be in bulldog in the long run (though name, email e.t.c is, organization information is not)

**Comment by awsmsrc** [comment]
when they sign in should the invite be automatically accepted or should they see a button.
Invite acceptance currently only goes through an authenticated websocket so we are going to need some new method of interfacing for this

**Comment by awsmsrc** [comment]
@tommoor im doing this now, one edge case to be considered is existing slack users

**Comment by tommoor** [comment]
@awsmsrc tidied this up, merged for testing and found that it doesn't work at all with organization invites as it's expecting an ID in the JSON response that only exists for user invites
